/**
 * 100 Gründe, warum ich dich liebe – Platzhaltertexte.
 * Diese Liste kann jederzeit durch persönliche Sätze ersetzt werden.
 */
export const loveReasons: string[] = [
  "Weil du mein Zuhause bist.",
  "Weil du mich zum Lachen bringst.",
  "Weil du mich so nimmst, wie ich bin.",
  "Weil sich mit dir alles richtig anfühlt.",
  "Weil dein Lächeln meinen Tag rettet.",
  "Weil du meine Hand hältst, wenn es schwer wird.",
  "Weil du an mich glaubst.",
  "Weil du mir Mut machst.",
  "Weil du mir wirklich zuhörst.",
  "Weil du mich verstehst, ohne dass ich rede.",
  "Weil du meine beste Freundin bist.",
  "Weil du mich jeden Tag aufs Neue überraschst.",
  "Weil du so wunderbar du selbst bist.",
  "Weil deine Umarmung sich wie Heimat anfühlt.",
  "Weil du meine verrückten Ideen mitträgst.",
  "Weil du mit mir tanzt, auch ohne Musik.",
  "Weil du morgens neben mir aufwachst.",
  "Weil dein Blick mir Ruhe schenkt.",
  "Weil du mich zu einem besseren Menschen machst.",
  "Weil du mich jeden Tag aufs Neue wählst.",
  "Weil du meine Lieblingsgeschichte bist.",
  "Weil du mein Herz schneller schlagen lässt.",
  "Weil du mich auch an schlechten Tagen liebst.",
  "Weil du das letzte Stück immer mit mir teilst.",
  "Weil du meine kalten Füße erträgst.",
  "Weil du mit mir alt werden willst.",
  "Weil du meine Familie zu deiner gemacht hast.",
  "Weil du mich anlächelst, wenn ich aufwache.",
  "Weil du meine Tränen trocknest.",
  "Weil du mich nie alleine lässt.",
  "Weil du meine Gedanken zu Ende denkst.",
  "Weil du mich erdest, wenn ich abhebe.",
  "Weil du mit mir träumst.",
  "Weil du mir verzeihst.",
  "Weil du mich auch ungeschminkt am schönsten findest.",
  "Weil deine Stimme mich beruhigt.",
  "Weil du mein Lieblingsmensch bist.",
  "Weil du mich stolz machst.",
  "Weil du mit mir albern sein kannst.",
  "Weil du mir den ersten Kaffee bringst.",
  "Weil du meine Lieblingslieder kennst.",
  "Weil du mich festhältst, wenn die Welt wackelt.",
  "Weil du mir Geborgenheit gibst.",
  "Weil du mich zum Staunen bringst.",
  "Weil du immer für mich da bist.",
  "Weil du mit mir schweigen kannst.",
  "Weil du mein Abenteuer bist.",
  "Weil du mich auslachst und ich es liebe.",
  "Weil du mir das Gefühl gibst, genug zu sein.",
  "Weil du mit mir durch jeden Sturm gehst.",
  "Weil du an unsere Zukunft glaubst.",
  "Weil du mich umarmst, bevor ich es brauche.",
  "Weil du meine Welt heller machst.",
  "Weil du mir Heimat in einem Menschen bist.",
  "Weil du mich so liebst, wie ich bin.",
  "Weil du mir Frieden schenkst.",
  "Weil du jeden Raum schöner machst.",
  "Weil du mich nicht ändern willst.",
  "Weil dein Lachen ansteckend ist.",
  "Weil du mit mir Pläne schmiedest.",
  "Weil du mir treu bist.",
  "Weil du mich ernst nimmst.",
  "Weil du meine Hand suchst.",
  "Weil du mit mir die Welt sehen willst.",
  "Weil du mich beschützt.",
  "Weil du mir Sicherheit gibst.",
  "Weil du mit mir lebst, nicht nur neben mir.",
  "Weil du mir jeden Tag ein Grund zum Aufstehen bist.",
  "Weil du meine Sorgen leichter machst.",
  "Weil du an das Gute in mir glaubst.",
  "Weil du mit mir lachst, bis wir weinen.",
  "Weil du mich daran erinnerst, was wichtig ist.",
  "Weil du mein ruhiger Hafen bist.",
  "Weil du mir Raum zum Atmen gibst.",
  "Weil du meine Macken liebst.",
  "Weil du mit mir Eis isst, auch im Winter.",
  "Weil du mich tröstest, ohne Worte.",
  "Weil du mir das Wichtigste im Leben zeigst.",
  "Weil du mich anschaust, als wäre ich ein Wunder.",
  "Weil du mit mir Erinnerungen sammelst.",
  "Weil du mein Glück sein willst.",
  "Weil du mir den Rücken stärkst.",
  "Weil du mit mir betest und hoffst.",
  "Weil du mich vermisst, wenn ich weg bin.",
  "Weil du mir nach Hause leuchtest.",
  "Weil du mich so geduldig liebst.",
  "Weil du mir jeden Morgen Gutes wünschst.",
  "Weil du mit mir Kind sein kannst.",
  "Weil du mir vertraust.",
  "Weil du mein Lieblingsgrund zum Heimkommen bist.",
  "Weil du mir Hoffnung gibst.",
  "Weil du mich liebevoll an alles erinnerst.",
  "Weil du mit mir die kleinen Dinge feierst.",
  "Weil du mir die Welt zeigst, wie sie sein könnte.",
  "Weil du mein Versprechen für immer bist.",
  "Weil du mich hältst, ohne festzuhalten.",
  "Weil du mit mir lachst über Dinge von früher.",
  "Weil du mir zeigst, dass Liebe einfach sein kann.",
  "Weil du mein schönster Gedanke beim Einschlafen bist.",
  "Weil du mein erster Gedanke beim Aufwachen bist.",
  "Weil du einfach du bist – und das reicht für ein ganzes Leben.",
];
